### ISSUE TITLE
Refactor angular  version to remove depency on JQuery 

### ISSUE THREAD

**Issue by badre429** [aspnetboilerplate/module-zero-core-template#101]
the angular version has huge dependencies on JQuery on jquery plugin (toastr , ...) 
why not use @angular/material its getting ready for the production 

> it's unfaire to angular if you build asp.net mvc application the same for SPA

**Comment by ismcagdas** [comment]
Hi @badre429,

I understand your point very well about using jQuery in an angular project.
I also agree that angular is great but there will be always some missing components and people will need to use jQuery in angular apps (at least for now). So, we think this is also a good example of how to do that.

If you don't want those libraries on your project, you can delete them because we provide a template and you can freely modify it.

Thanks.

**Comment by ismcagdas** [comment]
We decided not to implement this in a short time, so we will consider it in the future.
