### ISSUE TITLE
3.0.0-beta2 can't login with angular

### ISSUE THREAD

**Issue by fileman** [aspnetboilerplate/module-zero-core-template#104]
I've downloaded template with lastest commit "Disable EF core global query filters while inserting seed data."
With MVC client no problem, Swagger is ok, but Angular loop in login page, no helpfull information in log, Model is valid, Policy exec succesfully

**Comment by hikalkan** [comment]
Thank you for the feedback. We haven't worked on Angular side yet. Will try to fix it.

**Comment by fileman** [comment]
thanks, have you planned to publish as Beta template on site? (with project name customization)
Another error in template, Test project has warning due to missing package reference in Castle.Core, to solve add "system.componentmodel.typeconverter -v 4.3.0" manually.

**Comment by hikalkan** [comment]
Fixed with https://github.com/aspnetboilerplate/module-zero-core-template/commit/2d1ca3a29023c015a547c0bd8c5bc1dfa20a4b52

**Comment by hikalkan** [comment]
> have you planned to publish as Beta template on site

It requires additional work (for the project generator on the web site). We may make this feature (being able to download prereleases) in the future but not possible now.

Another error in template, Test project has warning due to missing package reference in Castle.Core, to solve add "system.componentmodel.typeconverter -v 4.3.0" manually.

OK, we will make this change.
