### ISSUE TITLE
Run angular project on visual studio 2017

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero-core-template#18]
Is it possible to run the angular project in visual studio?

I tried through F5, but I got the following error:

![image](https://cloud.githubusercontent.com/assets/5401232/24003250/bce4f1ce-0a41-11e7-9306-4c28990f0cd6.png)

Besides, I would like to know how to publish it to azure.

Thanks in advance!

**Comment by hikalkan** [comment]
Not possible since it uses angular-cli which has it's own runtime.

"ng build" command is used to publish solution to dist folder. Then you can upload file to azure.
You can find more on the web to know how to publish a project with angular-cli to azure, we use Google's standard angular-cli tooling.
