### ISSUE TITLE
Reworking Tenant Selection - How can to get a list of users

### ISSUE THREAD

**Issue by iamseanduffy** [aspnetboilerplate/module-zero-core-template#280]
Manually selecting a tenant during the login process does not work for us as it is an extra step for ours users.

We intend to remove the tenancy selection option from the login screen and load the tenant ID programmatically from the user object.

We will ensure that the usernames have system wide uniqueness.

We have been trying to query a IRepository<User, long> in this manner:

```
public async Task<User> GetUserOrNullAsync(string userName)
{
   userName = userName.ToUpperInvariant();
   return await _userRepository.FirstOrDefaultAsync(user => user.NormalizedUserName == userName);
}
```

However the query only returns a result if the AbpSession.TenantId has been set to the correct tenant.

Questions:  
How can we query against all users, regardless of the tenant they belong to?
What was the reason for making the tenant selection a manual process?
Would your team be interested in making the tenant selection mechanism more dynamic?

**Comment by Worthy7** [comment]
The reason you cannot find a user, is because DataFilers are limiting your search only to those in the same.
DataFilters should not be enabled until the user is logged in... so this shouldn't be happening. Are you sure they are logged out when this code runs?
Are you sure you even need MultiTenancy? What is the context of your users? (Internet? University? B2B?)

> How can we query against all users, regardless of the tenant they belong to?

Your code should work. Something else is stopping it. Either the user is already logged in, or some datafilers are set up.

**Comment by ryancyq** [comment]
Hi @iamseanduffy , you may disable `MayHaveTenant` data filter.
Also, you are not required to normalize the input `username` as it is handled in [AbpUserStore.cs#L293](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs#L293) which was used in `AbpUserManager`
```c#
public virtual async Task<User> GetUserOrNullAsync(string userName)
{
    using (_unitOfWorkManager.Current.DisableFilter(AbpDataFilters.MayHaveTenant))
    {
        return await _userManager.FindByNameAsync(userName);
    }
}
```
