### ISSUE TITLE
Unnecessary package references in Project.Abp.Core

### ISSUE THREAD

**Issue by sh4nji** [aspnetboilerplate/module-zero-core-template#404]
Hello,

I have something I don't understand.

To my knowledge the Core project should only include the domain classes as defined by DDD. I was bit confused why there are so many package references.

To my understanding of onion architecture + DDD:
- AutoMapper should be referenced in the Application layer.
- The EntityFramework configuration should be part of the EntityFrameworkCore project.
- Dependency injection configuration should be at the application level, so why do I need Castle.Windsor?

Maybe I'm wrong here, but then I don't understand something. Or is Core not the domain layer but just a shared assembly?

**Comment by hikalkan** [comment]
Hi @sh4nji,

Core is the domain layer, you are right. Let me go one by one:

>AutoMapper should be referenced in the Application layer

Application layer uses AutoMapper for DTO-Entity mappings generally. However, domain layer may also need to object to object mapping and we may want to use auto mapping instead of manual way. So, I think Object2Object mapping can be needed in any layer.
I don't remember where it's needed, you can see by removing `Abp.AutoMapper` from the Core project to see what error you are getting.

>The EntityFramework configuration should be part of the EntityFrameworkCore project

EntityFrameworkCore reference is there to make possible to use EF Core's async LINQ extension methods like ToListAsync, FirstOrDefaultAsync... etc. Most of the people are not aware those methods are part of EF Core and ask us why they can't use these methods (they think it is an ABP restriction). So, we decided to add EntityFrameworkCore  to the domain layer. However, all the EF Core configuration and other EF Core related stuff is in the .EntityFrameworkCore project.
You can easily remove EntityFrameworkCore dependency if you want to strictly follow the best practices. Sometimes, we make some minor exceptions to be more practical to developers.

> Dependency injection configuration should be at the application level, so why do I need Castle.Windsor

Castle.Windsor is a core dependency of the AspNet Boilerplate framework. Even the most core Abp package depends on it. So, unfortunately, no way of removing castle dependency. `Castle.Windsor.MsDependencyInjection` can be moved to the web layer, but this does not break castle dependency of your solution.
