### ISSUE TITLE
Does not render properly in Edge

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-core-template#63]
see https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2225

**Comment by prom3theu5** [comment]
It's due to the way the icons have been imported.
I fixed it by delivering my icons from google cdn with       
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`
instead of the local css file.

The reason for this is because google deliver a user-agent specific css file to the browser when requesting that link.
As far as I can tell the only difference is the edge css does not have:
`-webkit-font-smoothing: antialiased;`
included in it.

**Comment by hikalkan** [comment]
Thank you very much for the information you shared. It would be time consuming for us to understand the reason. We will fix this.

**Comment by jamesatgithub** [comment]
hi with the latest 2.3 template I still got the render issue in Edge on Login and the Dashboard. compared the google css downloaded with Edge and fixed the materialicons.css like below, then worked

`/* fallback */
@font-face {
    font-family: 'Material Icons';
    font-style: normal;
    font-weight: 400;
    src: local('Material Icons'), local('MaterialIcons-Regular'), url(materialicons.woff2) format('woff2');
}

.material-icons {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    line-height: 1;
    letter-spacing: normal;
    text-transform: none;
    display: inline-block;
    white-space: nowrap;
    word-wrap: normal;
    direction: ltr;
    font-feature-settings: 'liga';
    /*-webkit-font-feature-settings: 'liga';
    -webkit-font-smoothing: antialiased;*/
}`

**Comment by ismcagdas** [comment]
Thanks @jamesatgithub , let us check and fix this.
